version: '3'
services:
    gameserver:
        image: registry-vpc.cn-chengdu.aliyuncs.com/longfei1/tankbattle-server
        working_dir: /data/service/server/build
        ports:
            - "8888:8888"
            - "9000:9000"
        stdin_open: true
        tty: true
        command:
            - ./server.out

    gameproxy:
        image: registry-vpc.cn-chengdu.aliyuncs.com/longfei1/tankbattle-server
        working_dir: /data/service/proxy/build
        ports:
            - "8889:8889"
            - "9001:9001"
        stdin_open: true
        tty: true
        command:
            - ./proxy.out